### ISSUE TITLE
Can't convert python code for Barcodescanner to APK using Google Colab (with Kivy and buildozer)

### ISSUE THREAD

**Issue by 2022Mark2022** [vijethph/Barcode-Scanner#2]
Hi Vijeth,
I want to install a barcode scanner app on my android phone. I managed to install the barcode APK from this github page (https://github.com/vijethph/Barcode-Scanner/releases) on my android phone and it worked. 

However when I used your python script and converted the .py script to an APK file using Google Colab I was not able to install the barcode scanner app on my phone eventhough I allowed install from 3rd parties. Currently I am using python 3.10.9. Do you have any idea how to solve this issue?

Many thanks in advance,

Mark

**Comment by vijethph** [comment]
Hi Mark,

The project was initially designed to see if it was possible to build Android APK from Python itself, rather than relying on Java. We tried using a library called python-for-android, but for some reason, it didn't work as expected. Hence it was dropped, and we built Android APK using Java. The desktop application was built in Python.

To build Android APK using Python, please refer python-for-android documentation: https://python-for-android.readthedocs.io/en/latest/.
For any issues / errors related to this, please contact the people maintaining this library at https://github.com/kivy/python-for-android.

Thank you.
